
services:

  database:
    container_name: database
    image: mysql:latest
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - microservices-network

networks:
   microservices-network:   
   


volumes:
  db: