
spring:
  http:
    multipart:
      enabled: false
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    databaseName: "PencaUcu"
    connectionString: "jdbc:mysql://localhost:3306/"
    databaseUsername: "root"
    databasePassword: "root"