
jwtSecurity:
  JWT_SECRET_KEY: "b0KuPuLw77Z0hQhCsK-GTHoEx_kethtn357V7iqwEpCTIsLgqbBC_vQBTGC6M5rINl0FrqHK-D3cbOsMOlfyVKuQPvpyGcLcxAoLOTpYXc28nVwB7iBq2oKj9G9lHkFOUKn"
  encryptedPassword: "$2a$10$56VCAiApLO8NQYeOPiu2De/EBC5RWrTZvLl7uoeC3r7iXinRR1iiq"
  
spring:
  multipart:
    enabled: false
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    databaseName: "PencaUCU"
    connectionString: "jdbc:mysql://localhost:3306/"
    databaseUsername: "root"
    databasePassword: "1234"
  mail:
    host: "smtp.gmail.com"
    port: "587"
    username: "pencaucuprueba@gmail.com"
    password: "zdsn vtoo deni xhyb"
    password2: "PencaUcuPrueba123"
    body: "Estimado, usted esta recibiendo este mensaje debido a que esta inscripto en la aplicacion PencaUCU.\n
  Estos son los partidos del dia y que aun está a tiempo de predecir: "
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org:
      springframework:
        web:
        filter:
          CommonsRequestLoggingFilter: DEBUG
